<div class="table-message">
    <h1>Customers</h1>
    <?php echo $this->getContent("tables/search_helper"); ?>
</div>
<table id="cust">
    <thead>
        <tr>
            <th>Customer</th>
            <th>Contact Last Name</th>
            <th>Contact First Name</th>
            <th>Phone</th>
            <th>Address Line 1</th>
            <th>Address Line 2</th>
            <th>City</th>
            <th>State</th>
            <th>Postal Code</th>
            <th>Country</th>
            <th>Sales Rep</th>
            <th>Credit Limit</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>