<div class="table-message">
    <h1>Employees</h1>
    <?php echo $this->getContent("tables/search_helper"); ?>
</div>
<table id="emp">
    <thead>
        <tr>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Extension</th>
            <th>Email</th>
            <th>City</th>
            <th>Title</th>
            <th>Reports To</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>