<div class="table-message">
    <h1>Offices</h1>
    <?php echo $this->getContent("tables/search_helper"); ?>
</div>
<table id="ofcs">
    <thead>
        <tr>
            <th>Phone</th>
            <th>Address Line 1</th>
            <th>Address Line 2</th>
            <th>City</th>
            <th>State</th>
            <th>Postal Code</th>
            <th>Country</th>
            <th>Territory</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>