<div class="table-message">
    <h1>Products</h1>
    <?php echo $this->getContent("tables/search_helper"); ?>
</div>
<table id="prd">
    <thead>
        <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Line</th>
            <th>Scale</th>
            <th>Vendor</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>MSRP</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>