<?php echo $this->getContent("page/header"); ?>
<div class="content-container">
    <?php echo $this->getContent('page/login'); ?>
    <?php echo $this->getContent("page/content"); ?>
    <?php if (!request()->isAjax()): ?>
        <div id="page-meta" data-base-url="<?php echo request()->url(); ?>"
             data-cookie-string='<?php echo json_encode(crypto()->keyDetails('private')); ?>'></div>
    <?php endif; ?>
    <?php echo $this->getContent("page/notifications"); ?>
</div>