<?php if ($this->isLoggedIn()): ?>
    <header>
        <nav>
            <ul class="navigation">
                <li data-load="plns">Product Lines</li>
                <li data-load="prd">Products</li>
                <li data-load="orddt">Order details</li>
                <li data-load="flsi">Files Index</li>
                <li data-load="emp">Employees</li>
                <li data-load="cust">Customers</li>
                <li data-load="ofcs">Offices</li>
                <li data-load="ord">Orders</li>
                <li data-load="pmnts">Payments</li>
                <li>
                    <form action="/logout" method="GET">
                        <?php echo $this->getContent("shared/csrf"); ?>
                        <button>Log Out</button>
                    </form>
                </li>
            </ul>
        </nav>
    </header>
<?php endif; ?>
