<?php if (session()->getData('logged_in')): ?>
    <nav>
        <ul class="navigation">
            <li data-load="product_lines">Product Lines</li>
            <li data-load="products">Products</li>
            <li data-load="order_details">Order details</li>
            <li data-load="files_index">Files Index</li>
            <li data-load="employees">Employees</li>
            <li data-load="customers">Customers</li>
            <li data-load="offices">Offices</li>
            <li data-load="orders">Orders</li>
            <li data-load="payments">Payments</li>
        </ul>
    </nav>
<?php endif; ?>
<?php require_once(VIEWPATH . "page/login.phtml"); ?>
