<?php if (!$this->isLoggedIn()): ?>
    <div class="col-sm-4 col-sm-offset-4 login-box">
        <form class="login-form" role="form" action="/login" method="POST">
            <p>Please log in to continue.</p>
            <div class="form-group">
                <input class="form-control" type="text" name="username" placeholder="Email" title="Email"/>
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password" tiwwqtle="Email"/>
            </div>
            <button class="col-sm-12 btn btn-primary">Log In</button>
            <div class="clearfix"></div>
        </form>
    </div>
    <div class="clearfix"></div>
<?php endif; ?>